# Step 1: Use an official Node runtime as a parent image
FROM node:latest

# Create app directory
RUN mkdir -p /app

# Step 2: Set the working directory
WORKDIR /app

# Step 3: Copy package.json and install dependencies
COPY aviary/package.json ./
COPY aviary/package-lock.json ./
RUN npm install

# Step 4: Copy the rest of your app's source code
COPY . .

# Step 5: Your app binds to port 3001, so you'll use the EXPOSE instruction
EXPOSE 3001

# Step 6: Define the command to run your app
CMD [ "node", "server.js" ]
